from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSoru = QtWidgets.QLabel(Form)
        self.labelSoru.setObjectName("labelSoru")
        self.gridLayout.addWidget(self.labelSoru, 0, 0, 1, 2)
        self.textSoru = QtWidgets.QTextEdit(Form)
        self.textSoru.setObjectName("textSoru")
        self.gridLayout.addWidget(self.textSoru, 1, 0, 1, 2)
        self.labelSecenekler = QtWidgets.QLabel(Form)
        self.labelSecenekler.setObjectName("labelSecenekler")
        self.gridLayout.addWidget(self.labelSecenekler, 2, 0, 1, 1)
        self.optionsLayout = QtWidgets.QVBoxLayout()
        self.optionsLayout.setObjectName("optionsLayout")
        self.radio1 = QtWidgets.QRadioButton(Form)
        self.radio1.setObjectName("radio1")
        self.optionsLayout.addWidget(self.radio1)
        self.cevap1 = QtWidgets.QLineEdit(Form)
        self.cevap1.setObjectName("cevap1")
        self.optionsLayout.addWidget(self.cevap1)
        self.radio2 = QtWidgets.QRadioButton(Form)
        self.radio2.setObjectName("radio2")
        self.optionsLayout.addWidget(self.radio2)
        self.cevap2 = QtWidgets.QLineEdit(Form)
        self.cevap2.setObjectName("cevap2")
        self.optionsLayout.addWidget(self.cevap2)
        self.radio3 = QtWidgets.QRadioButton(Form)
        self.radio3.setObjectName("radio3")
        self.optionsLayout.addWidget(self.radio3)
        self.cevap3 = QtWidgets.QLineEdit(Form)
        self.cevap3.setObjectName("cevap3")
        self.optionsLayout.addWidget(self.cevap3)
        self.radio4 = QtWidgets.QRadioButton(Form)
        self.radio4.setObjectName("radio4")
        self.optionsLayout.addWidget(self.radio4)
        self.cevap4 = QtWidgets.QLineEdit(Form)
        self.cevap4.setObjectName("cevap4")
        self.optionsLayout.addWidget(self.cevap4)
        self.radio5 = QtWidgets.QRadioButton(Form)
        self.radio5.setObjectName("radio5")
        self.optionsLayout.addWidget(self.radio5)
        self.cevap5 = QtWidgets.QLineEdit(Form)
        self.cevap5.setObjectName("cevap5")
        self.optionsLayout.addWidget(self.cevap5)
        self.gridLayout.addLayout(self.optionsLayout, 3, 0, 1, 2)
        self.btnEkle = QtWidgets.QPushButton(Form)
        self.btnEkle.setObjectName("btnEkle")
        self.gridLayout.addWidget(self.btnEkle, 4, 0, 1, 1)
        self.btnKaydet = QtWidgets.QPushButton(Form)
        self.btnKaydet.setObjectName("btnKaydet")
        self.gridLayout.addWidget(self.btnKaydet, 4, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form - toplu.ui"))
        self.labelSoru.setText(_translate("Form", "Soru"))
        self.labelSecenekler.setText(_translate("Form", "Şıklar"))
        self.radio1.setText(_translate("Form", "1. Cevap"))
        self.radio2.setText(_translate("Form", "2. Cevap"))
        self.radio3.setText(_translate("Form", "3. Cevap"))
        self.radio4.setText(_translate("Form", "4. Cevap"))
        self.radio5.setText(_translate("Form", "5. Cevap"))
        self.btnEkle.setText(_translate("Form", "Soru Bankasına Ekle"))
        self.btnKaydet.setText(_translate("Form", "Soru Bankasını Kaydet"))